spring: #springboot???
    datasource: #?????
        name: test
        #127.0.0.1??????ip?3306?mysql?????serverTimezone???????????mysql???????????
        #useSSL???????mysql???????SSL??
        url: jdbc:mysql://127.0.0.1:3306/test?serverTimezone=GMT%2B8&useSSL=FALSE
        username: root  #???????root????
        password: root #?????????
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource

mybatis:  #mybatyis???
#    config:
#        location: mybatis-config.xml
    mapper-locations: classpath:mapper/*.xml #??mapper?????????mapper??????? xml???
    type-aliases-package: com.example.mybatisdemo.entity
